# Resource Template for Cybersecurity Resource Submission

Resource Name: "Resource Name"
Type: "Resource Type" # e.g., tool, blog, tutorial, etc.
Link: "https://example.com"
Authority: "high"  # Choose from high, medium, low
Popularity: "medium"  # Choose from high, medium, low
Category: "Category Name"  # e.g., threat intelligence, incident response, etc.
Author: "Author Name"
Last Updated: "YYYY-MM-DD"
Skill Level: "beginner"  # Choose from beginner, intermediate, advanced
Access: "free"  # Choose from free, freemium, paid 
Keywords:
  - keyword1
  - keyword2
  - keyword3
API: true  # Set true if the resource provides an API, false if not