name: Run Crawler Script

on:
  # This will schedule the workflow to run periodically based on cron syntax.
  schedule:
    - cron: '0 0 1 * *' # This will run the script every day at midnight (UTC).
  workflow_dispatch:  # This allows manual trigger in case you need it.
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 keybert

    # Run the script
    - name: Run Python script
      run: python crawler/main.py
